global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sonarqube"
    metrics_path: "/api/monitoring/metrics"
    static_configs:
      - targets: ["sonarqube:9000"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "minio"
    metrics_path: "/minio/v2/metrics/cluster"
    static_configs:
      - targets: ["minio-console:9000"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
